const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const bank=require('../data/questions.json');
if (process.env.EXITCODE_E2E !== '1') throw new Error('Set EXITCODE_E2E=1 only against an isolated test database; this check resets the event.');
const base=process.env.TEST_URL || 'http://127.0.0.1:5057';
(async()=>{
 const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
 const ctx=await browser.newContext({viewport:{width:1440,height:1000}});
 const adminCtx=await browser.newContext();const admin=await adminCtx.newPage(); const page=await ctx.newPage();
 const errors=[];page.on('pageerror',e=>errors.push(e.message));admin.on('pageerror',e=>errors.push(e.message));
 async function enter(){await page.bringToFront();await page.locator('#participant-enter').click();await page.waitForFunction(()=>window.ParticipantGuard?.active===true);}
 async function post(url,data){const r=await admin.request.post(base+url,{data});assert.equal(r.status(),200,await r.text());return r.json();}
 try{
 await admin.request.post(base+'/admin/login',{form:{username:'admin',password:'exitcode0_admin_2026'}});
 await post('/api/admin/reset-event',{confirmation:'RESET EVENT'});
 await page.goto(base+'/register');
 await page.locator('#register-tab').click();await page.locator('#reg-name').fill('Participant Flow QA');await page.locator('#reg-member1').fill('Ada');await page.locator('#reg-member2').fill('Lin');await page.locator('#team-register-form button[type=submit]').click();
 await page.waitForURL(/waiting/);assert.equal(await page.locator('#participant-gate').isVisible(),false);assert.equal(await page.locator('#lobby-check-btn').count(),0);
 await page.evaluate(()=>{window.dispatchEvent(new Event('blur'));document.dispatchEvent(new Event('fullscreenchange'));});
 let security=await (await page.request.get(base+'/api/fullscreen/status')).json();assert.equal(security.required,false);assert.equal(security.violations,0);
 const lateCtx=await browser.newContext();const latePage=await lateCtx.newPage();await latePage.goto(base+'/register');await latePage.locator('#register-tab').click();
 console.log('PASS registration and waiting room do not require fullscreen or count departures');
 await post('/api/admin/event-action',{action:'start'});await page.waitForURL(/arena/);
 await latePage.locator('#registration-closed-notice').waitFor({state:'visible'});
 assert.equal(await latePage.locator('#team-register-form button[type=submit]').isDisabled(),true);
 const rejected=await lateCtx.request.post(base+'/register',{form:{name:'Too late',member1:'X',member2:'Y'}});assert.equal(rejected.status(),403);
 await lateCtx.close();await enter();console.log('PASS event start closes open registration forms and rejects direct late POST');
 let progress=await (await page.request.get(base+'/api/team-progress')).json();assert.equal(progress.questions[0].is_answered,false);
 assert.equal(await page.locator('#cause').count(),0);assert.equal(await page.locator('#correction').getAttribute('type'),'text');
 for(let i=0;i<30;i+=6) assert.equal(progress.questions.slice(i,i+6).filter(q=>q.difficulty==='Difficult').length,1);
 for(const q of progress.questions) assert.equal(q.points,{Easy:20,Medium:25,Difficult:35}[q.difficulty]);
 const teamID=await page.locator('#arena').getAttribute('data-team-id');
 const first=bank.find(q=>q.id===progress.questions[0].id);const expectedScore=first.points-5;
 assert.equal(await page.locator('#question-task').innerText(),first.task);
 await page.locator('#error_location').fill(first.bug_location.match(/\d+/)[0]);await page.locator('#error_type').selectOption(first.error_type);await page.locator('#expected_output').fill(first.expected_output);await page.locator('#correction').fill(first.correction);
 await page.locator('[data-powerup=rubber-duck]').click();await page.locator('#confirm-accept').click();await page.waitForFunction(()=>!document.getElementById('rubber-duck-hint-box').hidden);
 assert.equal(Number(await page.locator('#arena-team-score').innerText()),-5);
 await page.locator('#commit-fix-btn').click();await page.locator('#confirm-accept').click();await page.waitForFunction(()=>document.getElementById('commit-fix-btn').disabled && !document.getElementById('answer-status').hidden);
 progress=await (await page.request.get(base+'/api/team-progress')).json();assert.equal(progress.questions[0].is_answered,true);assert.equal(progress.questions[0].hint_used,1);assert.equal(progress.questions[0].awarded_score,first.points);assert.equal(progress.questions[0].field_results.length,4);assert.equal(await page.locator('#answer-status .answer-breakdown li').count(),4);assert.equal(await page.locator('.field-result').count(),4);
 await page.reload();await enter();await page.waitForFunction(()=>document.getElementById('correction').disabled && document.getElementById('correction').value.length>0);assert.match(await page.locator('#answer-status').innerText(),/final/i);console.log('PASS final debugging answer, hint penalty, persisted status/response');
 await page.evaluate(()=>document.exitFullscreen());await page.waitForFunction(()=>document.getElementById('participant-violations').textContent.startsWith('1 /'));assert.equal(await page.locator('#participant-gate').isVisible(),true);
 const denied=await page.request.post(base+'/api/submit-bug-fix',{data:{question_id:progress.questions[1].id}});assert.equal(denied.status(),403);await enter();console.log('PASS first exit warns and gates submission until fullscreen restored');
 await post('/api/admin/event-action',{action:'end'});await page.goto(base+'/result');await enter();await page.locator('.debugging-review-question summary').first().click();assert.equal(await page.locator('.debugging-field').count(),4);await page.screenshot({path:'/tmp/exitcode-field-results.png',fullPage:true});assert.match(await page.locator('.rapid-fire-cta').getAttribute('class'),/btn-primary/);console.log('PASS individual results available after round ends and Rapid Fire action is prominent');await post('/api/admin/quiz-action',{action:'open'});
 await page.goto(base+'/quiz');await enter();await page.locator('#quiz-start').click();await page.waitForFunction(()=>!document.getElementById('quiz-play').hidden);
 for(let i=0;i<10;i++) {await page.locator('#quiz-options input').nth(0).check();await page.locator('#quiz-lock').click();if(i===0){await page.locator('#quiz-options .option-correct').waitFor();assert.equal(await page.locator('#quiz-options .option-incorrect').count(),1);assert.match(await page.locator('#quiz-options .option-correct').innerText(),/3/);await page.screenshot({path:'/tmp/exitcode-quiz-wrong-correct.png'});}if(i<9) await page.waitForFunction(n=>document.getElementById('quiz-progress-label').textContent.startsWith('QUESTION '+String(n).padStart(2,'0')),i+2);}
 await page.locator('#quiz-finish').waitFor({state:'visible'});assert.equal(await page.locator('.quiz-review-item').count(),10);
 assert.equal(await page.locator('#quiz-finish-action').getAttribute('href'),'#quiz-feedback');assert.equal(await page.locator('#quiz-results-link').isVisible(),false);
 await page.locator('#quiz-finish-action').click();assert.equal(await page.locator('#quiz-feedback-heading').evaluate(el=>document.activeElement===el),true);
 for(const id of ['clarity','difficulty','interface','pacing','enjoyment','overall']) await page.locator(`input[name=${id}][value="4"]`).check();
 await page.locator('#quiz-feedback-note').fill('Clear questions and helpful results.');await page.locator('#quiz-feedback-submit').click();await page.waitForFunction(()=>document.getElementById('quiz-feedback-status').textContent.includes('Feedback received'));
 await page.reload();await enter();await page.waitForFunction(()=>document.getElementById('quiz-feedback-submit').disabled);assert.equal(await page.locator('#quiz-feedback-note').inputValue(),'Clear questions and helpful results.');await page.screenshot({path:'/tmp/exitcode-quiz-feedback.png',fullPage:true});assert.equal(await page.locator('#quiz-finish-action').getAttribute('href'),'/leaderboard');assert.equal(await page.locator('#quiz-feedback-results').isVisible(),true);console.log('PASS feedback-first action changes to results only after saved feedback, and survives refresh');
 assert.equal(await page.locator('#quiz-feedback-form fieldset').count(),6);
 const feedbackCopy=await page.locator('#quiz-feedback-form').innerText();assert.match(feedbackCopy,/debugging/i);assert.match(feedbackCopy,/whole event/i);
 assert.equal(await page.locator('.quiz-review-options .option-correct').count(),10);
 await page.locator('#quiz-feedback-results').click();await page.waitForURL(/leaderboard/);await page.waitForFunction(()=>!App.navigation.loading);assert.equal(await page.locator('.rapid-fire-cta').count(),0);assert.equal(await page.evaluate(()=>!!document.fullscreenElement&&ParticipantGuard.active),true);
 await admin.goto(base+'/admin/dashboard#feedback');await admin.waitForFunction(()=>document.getElementById('admin-feedback-body').textContent.includes('Clear questions'));assert.equal(await admin.locator('#site-navigation a').filter({hasText:'Leaderboard'}).count(),0);assert.equal(await admin.locator('#site-navigation a').filter({hasText:'View website'}).count(),0);
 const exported=await admin.request.get(base+'/admin/export/feedback.csv');assert.equal(exported.status(),200);assert.match(await exported.text(),/Clear questions and helpful results/);
 await post('/api/admin/publish-results',{});console.log('PASS organizer feedback CSV, simplified navigation, and result publication');
 await page.evaluate(()=>document.exitFullscreen());await page.waitForFunction(()=>document.getElementById('participant-gate-title').textContent==='Account blocked');
 assert.equal((await page.request.get(base+'/api/team-progress')).status(),403);
 await admin.goto(base+'/admin/dashboard#security');await admin.locator('#admin-security-body [data-team-unban]').first().click();await admin.locator('#confirm-accept').click();
 await page.waitForFunction(()=>!document.getElementById('participant-enter').hidden);
 security=await (await page.request.get(base+'/api/fullscreen/status')).json();assert.equal(security.violations,0);assert.equal(security.blocked,false);await enter();
 assert.equal((await (await page.request.get(base+'/api/team-progress')).json()).score,expectedScore);
 console.log('PASS organizer unban after publication restores modal access and keeps score');
 await page.evaluate(()=>document.exitFullscreen());await page.waitForFunction(()=>document.getElementById('participant-violations').textContent.startsWith('1 /'));await enter();
 await page.evaluate(()=>document.exitFullscreen());await page.waitForFunction(()=>document.getElementById('participant-gate-title').textContent==='Account blocked');
 await page.goto(base+'/result');assert.ok(page.url().endsWith('/blocked'));
 await post('/api/admin/unban-team',{team_id:teamID});await page.locator('#blocked-recheck').click();await page.waitForURL(/result/);await enter();
 console.log('PASS blocked page also recovers after organizer unban without a reset');
 await page.evaluate(()=>document.exitFullscreen());await page.waitForFunction(()=>document.getElementById('participant-violations').textContent.startsWith('1 /'));await enter();
 await page.evaluate(()=>document.exitFullscreen());await page.waitForFunction(()=>document.getElementById('participant-gate-title').textContent==='Account blocked');
 await page.goto(base+'/logout');
 const relogin=await page.request.post(base+'/register',{form:{action:'login',team_lookup:'Participant Flow QA'}});assert.equal(relogin.status(),403);console.log('PASS second exit during quiz blocks across rounds and logout/login');
 assert.deepEqual(errors,[]);console.log('PASS no browser errors');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
